### PR TITLE
fix(github-templates): change  npm authentication mechanism 

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
use actions/setup-node to authenicate to GPM and pass token as an env variable. This seems to be
more accurate than using .npmrc in github

### CODE REVIEW

**Review by crazynammer — COMMENTED** [review]
For GitHub, why can't we do the same NPM authentication once globally instead of duplicating the logic in each job.  If this is limitation, then changes look good. 

`registry-url: 'https://npm.pkg.github.com'`

**Comment by azlam-abdulsalam** [comment]
@crazynammer  not sure how does that can be done globally? Have an example?

**Comment by vuha-acn** [comment]
@azlam-abdulsalam  - Potentially [composite run steps actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file) in GitHub.  See this [community post](https://github.community/t/run-common-task-in-github-action-or-alternative-of-before-script-in-github-workflow-ci/116433/3) as it's the reason behind I was thinking of it since GitLabs has the before_script option.

**Comment by azlam-abdulsalam** [comment]
@vuha-acn will address that in a future PR

**Pull request merged**
